### PR TITLE
Complete CRUD MVP

### PR DESCRIPTION
**Pull request by sampurcell**
@linkblaine @cdimartino 

I have some questions about redirect, I didn't really understand the explanation. Also, I'm still a little confused when to use string interpolation to display a Ruby variable, such as in a href

### CODE REVIEW

**Comment by cdimartino** [comment]
Please close @sampurcell

**Comment by cdimartino** [comment]
Please close this pull request so that I no longer have it in my @mentioned requests! 🙏🏼 🙉

**Comment by arcpetretta** [comment]
Your wish is my command! Hope all is well, @cdimartino.

**Comment by cdimartino** [comment]
🙇 thank you!! All is well here - hope you are crushing it! 💪

**Pull request closed without merging**
